services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: santosh
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  student-api:
    container_name: studentapi
    image: santoshpoptani/student-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/student
    ports:
      - "3000:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  frontend-react:
    container_name: frontend-react
    image: santoshpoptani/student-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:3002
    ports:
      - "3002:5173"
    depends_on:
      - student-api
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db:
